// Curated by hand, written independently — a selection, not an exhaustive
// archive. Chosen for being both historically significant and well-enough
// documented that we're confident in the detail given. Where an exact vote
// count is stated, it's a well-established, widely reported figure —
// otherwise we just say "Passed" or "Defeated" rather than guess a number.
// Shared between the Political History and Timeline pages.
export const LANDMARK_VOTES = [
  {
    year: 1911,
    date: "18 August 1911",
    theme: "Constitutional",
    title: "Parliament Act 1911",
    result: "Passed",
    outcome: "achieved",
    detail: "Stripped the House of Lords of its power to block most legislation, reducing it to a delaying power only, after the Lords rejected the 1909 \"People's Budget.\" The foundation of the Commons' modern primacy over the Lords.",
  },
  {
    year: 1918,
    date: "6 February 1918",
    theme: "Democratic Reform",
    title: "Representation of the People Act 1918",
    result: "Passed",
    outcome: "achieved",
    detail: "Nearly tripled the electorate at a stroke — giving the vote to all men over 21 and, for the first time, to women over 30 who met a property qualification.",
  },
  {
    year: 1928,
    date: "2 July 1928",
    theme: "Democratic Reform",
    title: "Representation of the People (Equal Franchise) Act 1928",
    result: "Passed",
    outcome: "achieved",
    detail: "Gave women the vote on exactly the same terms as men, at 21 — a decade after the partial, property-qualified franchise of 1918.",
  },
  {
    year: 1965,
    date: "8 November 1965",
    theme: "Social Reform",
    title: "Murder (Abolition of Death Penalty) Act 1965",
    result: "Passed",
    outcome: "achieved",
    detail: "Suspended the death penalty for murder in Great Britain, on a free vote rather than along party lines — made permanent by a further Commons vote in 1969.",
  },
  {
    year: 1967,
    date: "27 July 1967",
    theme: "Social Reform",
    title: "Sexual Offences Act 1967",
    result: "Passed",
    outcome: "achieved",
    detail: "Decriminalised homosexual acts in private between men over 21 in England and Wales, a decade after the Wolfenden Report first recommended it.",
  },
  {
    year: 1972,
    date: "5 February 1972",
    theme: "Europe",
    title: "European Communities Bill, Second Reading",
    result: "Passed",
    outcome: "achieved",
    detail: "Approved the principle of the UK joining the European Economic Community (the forerunner of the EU), which it did the following year, in 1973.",
  },
  {
    year: 1979,
    date: "28 March 1979",
    theme: "Confidence",
    title: "Vote of No Confidence in the Callaghan Government",
    result: "Lost, 311 to 310",
    outcome: "not_kept",
    detail: "The government lost by a single vote — the only UK government brought down by a Commons confidence vote since 1924. It triggered the general election that brought Margaret Thatcher to power.",
  },
  {
    year: 2003,
    date: "18 March 2003",
    theme: "Foreign Policy & War",
    title: "Iraq War — authorisation of military action",
    result: "Passed",
    outcome: "achieved",
    detail: "MPs voted to authorise military action in Iraq, after one of the largest backbench rebellions in Labour Party history against Tony Blair's own government.",
  },
  {
    year: 2004,
    date: "18 November 2004",
    theme: "Social Reform",
    title: "Hunting Act — final Commons stages",
    result: "Passed",
    outcome: "achieved",
    detail: "Banned hunting foxes, deer, and hares with dogs in England and Wales, after years of deadlock with the Lords — eventually forced through using the rarely-invoked Parliament Act.",
  },
  {
    year: 2011,
    date: "15 September 2011",
    theme: "Constitutional",
    title: "Fixed-term Parliaments Act 2011",
    result: "Passed",
    outcome: "achieved",
    detail: "Set fixed five-year terms for Parliament, ending the Prime Minister's ability to call a snap election at will. Proved unpopular in practice and was repealed in 2022, restoring the previous system.",
  },
  {
    year: 2013,
    date: "5 February 2013",
    theme: "Social Reform",
    title: "Marriage (Same Sex Couples) Bill, Second Reading",
    result: "Passed by a large majority",
    outcome: "achieved",
    detail: "Legalised same-sex marriage in England and Wales, though the vote split the Conservative Party — more of its MPs voted against or abstained than voted in favour.",
  },
  {
    year: 2013,
    date: "29 August 2013",
    theme: "Foreign Policy & War",
    title: "Possible military action in Syria",
    result: "Government motion defeated",
    outcome: "not_kept",
    detail: "A rare government defeat on a matter of war and peace, widely seen as a significant moment for Parliament's role in decisions about military intervention.",
  },
  {
    year: 2017,
    date: "29 March 2017",
    theme: "Europe",
    title: "Article 50 (Notification of Withdrawal) Bill",
    result: "Passed",
    outcome: "achieved",
    detail: "Authorised the government to formally notify the EU of the UK's intention to leave, starting the two-year countdown to Brexit following the 2016 referendum.",
  },
  {
    year: 2019,
    date: "15 January 2019",
    theme: "Europe",
    title: "\"Meaningful Vote\" on Theresa May's Brexit Withdrawal Agreement",
    result: "Defeated, 432 to 202",
    outcome: "not_kept",
    detail: "A margin of 230 votes — the largest government defeat in the history of the House of Commons.",
  },
  {
    year: 2019,
    date: "20 December 2019",
    theme: "Europe",
    title: "European Union (Withdrawal Agreement) Bill, Third Reading",
    result: "Passed, 358 to 234",
    outcome: "achieved",
    detail: "Passed easily after Boris Johnson's landslide 2019 election win, clearing the way for the UK to formally leave the EU on 31 January 2020.",
  },
  // Economic history is its own huge subject — these are our own editorial
  // judgement calls for the votes and Acts with the clearest, longest-lasting
  // effect on how the UK economy actually works, not an official "top list."
  {
    year: 1846,
    date: "26 June 1846",
    theme: "Economic",
    title: "Importation Act 1846 (Repeal of the Corn Laws)",
    result: "Passed",
    outcome: "achieved",
    detail: "Scrapped tariffs that had protected British agriculture, opening the country up to free trade in food. It split Robert Peel's own Conservative Party so badly that it fell from power within weeks — a rupture that shaped British party politics for a generation.",
  },
  {
    year: 1910,
    date: "29 April 1910",
    theme: "Economic",
    title: "The \"People's Budget\" (Finance (1909–10) Act 1910)",
    result: "Passed",
    outcome: "achieved",
    detail: "David Lloyd George's budget introduced new taxes on high incomes and land to fund welfare reforms. The Lords' unprecedented rejection of it triggered the constitutional crisis that produced the Parliament Act 1911.",
  },
  {
    year: 1946,
    date: "14 February 1946",
    theme: "Economic",
    title: "Bank of England Act 1946",
    result: "Passed",
    outcome: "achieved",
    detail: "Nationalised the Bank of England, bringing UK monetary policy directly under government control — the first of Clement Attlee's wave of post-war nationalisations.",
  },
  {
    year: 1980,
    date: "8 August 1980",
    theme: "Economic",
    title: "Housing Act 1980 (Right to Buy)",
    result: "Passed",
    outcome: "achieved",
    detail: "Gave council tenants the legal right to buy their home at a discount. Reshaped home ownership in Britain and remains one of the most consequential — and contested — economic policies of the Thatcher era.",
  },
  {
    year: 1998,
    date: "23 April 1998",
    theme: "Economic",
    title: "Bank of England Act 1998",
    result: "Passed",
    outcome: "achieved",
    detail: "Gave the Bank of England independent control over setting interest rates, removing that power from the Chancellor — a fundamental change in how UK economic policy is made, still in place today.",
  },
  {
    year: 1998,
    date: "31 July 1998",
    theme: "Economic",
    title: "National Minimum Wage Act 1998",
    result: "Passed",
    outcome: "achieved",
    detail: "Introduced a legal minimum hourly wage in the UK for the first time, a flagship reform of the first Blair government.",
  },
  {
    year: 2008,
    date: "21 February 2008",
    theme: "Economic",
    title: "Banking (Special Provisions) Act 2008",
    result: "Passed",
    outcome: "achieved",
    detail: "Emergency legislation, rushed through Parliament in days, that nationalised Northern Rock — the first bank failure of the 2008 financial crisis and a turning point in the UK's response to it.",
  },
  {
    year: 2021,
    date: "20 October 2021",
    theme: "Economic",
    title: "Health and Social Care Levy Act 2021",
    result: "Passed",
    outcome: "achieved",
    detail: "Raised National Insurance to fund the NHS and social care — a significant tax rise, and a break from a Conservative manifesto pledge. Reversed the following year amid a wider economic crisis.",
  },
  {
    year: 1972,
    date: "17 March 1972",
    theme: "Economic",
    title: "Finance Act 1972 (introduction of VAT)",
    result: "Passed",
    outcome: "achieved",
    detail: "Introduced Value Added Tax, replacing Purchase Tax ahead of EEC entry. VAT remains one of the government's largest single sources of revenue over 50 years later.",
  },
  {
    year: 1984,
    date: "26 July 1984",
    theme: "Economic",
    title: "Trade Union Act 1984",
    result: "Passed",
    outcome: "achieved",
    detail: "Required trade unions to hold a secret ballot of members before calling a strike — part of a wider run of Thatcher-era union reform that permanently changed UK industrial relations law.",
  },
  // Constitutional history beyond the two entries above — how power is
  // actually structured and checked, not just who holds it.
  {
    year: 1949,
    date: "16 December 1949",
    theme: "Constitutional",
    title: "Parliament Act 1949",
    result: "Passed",
    outcome: "achieved",
    detail: "Cut the House of Lords' delaying power over legislation from two years to one, using the mechanism of the 1911 Act itself. Clement Attlee's government used it to push through Lords reform the Lords itself opposed.",
  },
  {
    year: 1958,
    date: "30 April 1958",
    theme: "Constitutional",
    title: "Life Peerages Act 1958",
    result: "Passed",
    outcome: "achieved",
    detail: "Allowed the Crown to create peers whose title isn't inherited — and, for the first time, allowed women to sit in the House of Lords. Life peerages are now how the large majority of new peers are appointed.",
  },
  {
    year: 1998,
    date: "9 November 1998",
    theme: "Constitutional",
    title: "Human Rights Act 1998",
    result: "Passed",
    outcome: "achieved",
    detail: "Wrote the European Convention on Human Rights directly into UK law, letting people enforce those rights in UK courts rather than having to go to Strasbourg. A recurring flashpoint in UK constitutional debate ever since.",
  },
  {
    year: 1998,
    date: "19 November 1998",
    theme: "Constitutional",
    title: "Scotland Act 1998",
    result: "Passed",
    outcome: "achieved",
    detail: "Established the Scottish Parliament, following the 1997 devolution referendum — the single biggest transfer of power out of Westminster in modern UK history.",
  },
  {
    year: 1999,
    date: "11 November 1999",
    theme: "Constitutional",
    title: "House of Lords Act 1999",
    result: "Passed",
    outcome: "achieved",
    detail: "Removed the automatic right of most hereditary peers to sit in the House of Lords, cutting their number from over 700 to 92 — the biggest reform of the Lords' membership in a century.",
  },
  {
    year: 2005,
    date: "24 March 2005",
    theme: "Constitutional",
    title: "Constitutional Reform Act 2005",
    result: "Passed",
    outcome: "achieved",
    detail: "Created the UK Supreme Court, separating the country's highest court from the House of Lords, and reformed the ancient office of Lord Chancellor to strengthen the separation of powers.",
  },
  // More of the long fight over who actually gets to vote, and how.
  {
    year: 1832,
    date: "7 June 1832",
    theme: "Democratic Reform",
    title: "Representation of the People Act 1832 (the \"Great Reform Act\")",
    result: "Passed",
    outcome: "achieved",
    detail: "Abolished many \"rotten boroughs\" with tiny or nonexistent electorates and redistributed seats to growing industrial cities, while modestly widening the franchise. The starting point of the UK's modern electoral system.",
  },
  {
    year: 1872,
    date: "18 July 1872",
    theme: "Democratic Reform",
    title: "Ballot Act 1872",
    result: "Passed",
    outcome: "achieved",
    detail: "Introduced the secret ballot for UK elections, ending open voting and the intimidation and bribery it had enabled for centuries.",
  },
  {
    year: 1969,
    date: "17 July 1969",
    theme: "Democratic Reform",
    title: "Representation of the People Act 1969",
    result: "Passed",
    outcome: "achieved",
    detail: "Lowered the voting age from 21 to 18, enfranchising millions of young people in time for the 1970 general election.",
  },
  {
    year: 2015,
    date: "26 March 2015",
    theme: "Democratic Reform",
    title: "Recall of MPs Act 2015",
    result: "Passed",
    outcome: "achieved",
    detail: "Let constituents force a by-election if their MP is convicted of an offence or suspended from the Commons for serious misconduct, by gathering enough signatures in a recall petition.",
  },
  // The welfare state and social change — bills that changed how people
  // actually live, not just how Parliament works.
  {
    year: 1944,
    date: "3 August 1944",
    theme: "Social Reform",
    title: "Education Act 1944 (the \"Butler Act\")",
    result: "Passed",
    outcome: "achieved",
    detail: "Established free secondary education for all children in England and Wales, and created the tripartite grammar/secondary modern/technical school system — the foundation of the modern state education system.",
  },
  {
    year: 1946,
    date: "6 November 1946",
    theme: "Social Reform",
    title: "National Health Service Act 1946",
    result: "Passed",
    outcome: "achieved",
    detail: "Created the NHS, launched on 5 July 1948 — free healthcare at the point of use for everyone, funded through taxation. Arguably the single most consequential piece of social legislation in modern UK history.",
  },
  {
    year: 1967,
    date: "27 October 1967",
    theme: "Social Reform",
    title: "Abortion Act 1967",
    result: "Passed",
    outcome: "achieved",
    detail: "Legalised abortion in Great Britain up to a set time limit, under specified medical grounds — one of a cluster of liberalising social reforms passed in the same Parliament as the Sexual Offences Act.",
  },
  {
    year: 1970,
    date: "29 May 1970",
    theme: "Social Reform",
    title: "Equal Pay Act 1970",
    result: "Passed",
    outcome: "achieved",
    detail: "Made it illegal to pay women less than men for the same or broadly similar work — prompted in part by the 1968 Ford Dagenham sewing machinists' strike.",
  },
  {
    year: 1975,
    date: "12 November 1975",
    theme: "Social Reform",
    title: "Sex Discrimination Act 1975",
    result: "Passed",
    outcome: "achieved",
    detail: "Made it unlawful to discriminate on the grounds of sex in employment, education, and the provision of goods and services, and created the Equal Opportunities Commission to enforce it.",
  },
  {
    year: 2004,
    date: "1 July 2004",
    theme: "Social Reform",
    title: "Gender Recognition Act 2004",
    result: "Passed",
    outcome: "achieved",
    detail: "Let transgender people apply for legal recognition of their acquired gender, including a new birth certificate — a legal framework that remains a live and contested political topic.",
  },
  {
    year: 2010,
    date: "8 April 2010",
    theme: "Social Reform",
    title: "Equality Act 2010",
    result: "Passed",
    outcome: "achieved",
    detail: "Consolidated decades of separate UK anti-discrimination law — covering sex, race, disability, age, religion and more — into a single Act.",
  },
  // More recent decisions on the use of British military force.
  {
    year: 2011,
    date: "21 March 2011",
    theme: "Foreign Policy & War",
    title: "Military intervention in Libya",
    result: "Passed by a large majority",
    outcome: "achieved",
    detail: "MPs backed UK participation in NATO-led air operations to protect civilians during the Libyan civil war, under a UN Security Council resolution — with cross-party support far wider than the 2003 Iraq vote.",
  },
  {
    year: 2015,
    date: "2 December 2015",
    theme: "Foreign Policy & War",
    title: "Extending UK airstrikes against ISIL to Syria",
    result: "Passed, 397 to 223",
    outcome: "achieved",
    detail: "Authorised RAF airstrikes against Islamic State targets in Syria as well as Iraq, after a heated debate remembered in part for Labour MP Hilary Benn's widely-reported speech backing the motion against his own leader's position.",
  },
  // More of the long, unfinished argument over Britain's place in Europe.
  {
    year: 1975,
    date: "9 April 1975",
    theme: "Europe",
    title: "Commons vote endorsing renegotiated EEC membership terms",
    result: "Passed by a large majority",
    outcome: "achieved",
    detail: "MPs backed the Wilson government's renegotiated terms of EEC membership ahead of the UK's first-ever national referendum two months later, despite a large rebellion of anti-EEC Labour MPs.",
  },
  {
    year: 1993,
    date: "23 July 1993",
    theme: "Europe",
    title: "Confidence vote following the Maastricht Treaty Social Chapter defeat",
    result: "Won, 339 to 299",
    outcome: "achieved",
    detail: "John Major staked his government's survival on ratifying the Maastricht Treaty after losing a vote on the Social Chapter opt-out the night before — winning, but only after turning it into an explicit confidence vote against his own famously rebellious backbenchers.",
  },
  {
    year: 2015,
    date: "17 December 2015",
    theme: "Europe",
    title: "European Union Referendum Act 2015",
    result: "Passed",
    outcome: "achieved",
    detail: "Legislated for the referendum that took place on 23 June 2016 — the Act that made the Brexit vote happen in the first place.",
  },
  // Two more moments when a government's survival itself was on the line.
  {
    year: 1924,
    date: "8 October 1924",
    theme: "Confidence",
    title: "Defeat of the first MacDonald Labour Government (the \"Campbell Case\")",
    result: "Lost, 364 to 198",
    outcome: "not_kept",
    detail: "Ramsay MacDonald's first, minority Labour government fell over its handling of a dropped prosecution against a communist newspaper editor — triggering the general election referenced in the Callaghan entry above as the last time this had happened before 1979.",
  },
  {
    year: 1940,
    date: "8 May 1940",
    theme: "Confidence",
    title: "The Norway Debate",
    result: "Won, 281 to 200",
    outcome: "achieved",
    detail: "Neville Chamberlain technically won this vote on the Commons' handling of the failed Norway campaign, but his majority collapsed from over 200 to just 81 as his own MPs voted against or abstained. He resigned two days later; Winston Churchill became Prime Minister.",
  },
  // Reaching further back — the constitutional and social foundations that
  // the rest of this list builds on.
  {
    year: 1689,
    date: "December 1689",
    theme: "Constitutional",
    title: "Bill of Rights 1689",
    result: "Passed",
    outcome: "achieved",
    detail: "Set hard limits on royal power after the Glorious Revolution — no suspending laws or raising taxes without Parliament's consent, and free elections and free speech within Parliament. The bedrock of the UK's constitutional monarchy.",
  },
  {
    year: 1701,
    date: "1701",
    theme: "Constitutional",
    title: "Act of Settlement 1701",
    result: "Passed",
    outcome: "achieved",
    detail: "Secured the Protestant succession to the throne and, just as importantly, guaranteed judges could only be removed by Parliament rather than at the monarch's pleasure — a founding pillar of judicial independence.",
  },
  {
    year: 1707,
    date: "1707",
    theme: "Constitutional",
    title: "Acts of Union 1707",
    result: "Passed",
    outcome: "achieved",
    detail: "Merged the Parliaments of England and Scotland into a single Parliament of Great Britain at Westminster — the union this site's own subject, the UK Parliament, is built on.",
  },
  {
    year: 1800,
    date: "1800",
    theme: "Constitutional",
    title: "Act of Union 1800",
    result: "Passed",
    outcome: "achieved",
    detail: "Merged the Parliament of Ireland into Westminster, creating the United Kingdom of Great Britain and Ireland from 1801. Partially undone over a century later by Irish independence in 1922.",
  },
  {
    year: 1829,
    date: "13 April 1829",
    theme: "Democratic Reform",
    title: "Roman Catholic Relief Act 1829 (\"Catholic Emancipation\")",
    result: "Passed",
    outcome: "achieved",
    detail: "Ended centuries of exclusion by allowing Catholics to sit as MPs and hold most public offices — pushed through by the Duke of Wellington's government despite his own party's deep opposition.",
  },
  {
    year: 1833,
    date: "28 August 1833",
    theme: "Social Reform",
    title: "Slavery Abolition Act 1833",
    result: "Passed",
    outcome: "achieved",
    detail: "Abolished slavery across most of the British Empire, building on the 1807 Act that had already ended Britain's own participation in the slave trade. The government paid £20 million in compensation — to slave owners, not the enslaved.",
  },
  {
    year: 1875,
    date: "11 August 1875",
    theme: "Social Reform",
    title: "Public Health Act 1875",
    result: "Passed",
    outcome: "achieved",
    detail: "Set binding sanitation, sewerage and housing standards for the first time, forcing local authorities to act — a direct response to the cholera outbreaks and squalor of the rapidly industrialising Victorian city.",
  },
  {
    year: 1888,
    date: "13 August 1888",
    theme: "Constitutional",
    title: "Local Government Act 1888",
    result: "Passed",
    outcome: "achieved",
    detail: "Created directly elected county councils across England and Wales, including the London County Council — the foundation of the modern local government system this site's data still sits alongside today.",
  },
  {
    year: 1908,
    date: "1 August 1908",
    theme: "Social Reform",
    title: "Old-Age Pensions Act 1908",
    result: "Passed",
    outcome: "achieved",
    detail: "Introduced Britain's first state pension — a modest, means-tested payment for the over-70s, but the first time the state took direct responsibility for supporting people in old age. A forerunner of the 1909 People's Budget that helped fund it.",
  },
  {
    year: 1922,
    date: "31 March 1922",
    theme: "Constitutional",
    title: "Irish Free State (Agreement) Act 1922",
    result: "Passed",
    outcome: "achieved",
    detail: "Gave legal effect to the Anglo-Irish Treaty, creating the Irish Free State as a self-governing dominion and partitioning Ireland — ending the Irish War of Independence, and one of the most consequential and contested Acts this Parliament has ever passed.",
  },
  {
    year: 2000,
    date: "11 May 2000",
    theme: "Constitutional",
    title: "Greater London Authority Act 1999",
    result: "Passed",
    outcome: "achieved",
    detail: "Created the directly elected Mayor of London and the London Assembly, restoring city-wide government to the capital for the first time since the Greater London Council was abolished in 1986.",
  },
  {
    year: 2011,
    date: "16 February 2011",
    theme: "Democratic Reform",
    title: "Parliamentary Voting System and Constituencies Act 2011",
    result: "Passed",
    outcome: "achieved",
    detail: "The enabling legislation for the 2011 referendum on switching Westminster elections to the Alternative Vote — a Liberal Democrat coalition priority. The referendum itself was heavily defeated, and the UK kept first-past-the-post.",
  },
  // A second pass, widening every category further.
  {
    year: 1857,
    date: "28 August 1857",
    theme: "Social Reform",
    title: "Matrimonial Causes Act 1857",
    result: "Passed",
    outcome: "achieved",
    detail: "Created civil divorce for the first time — before this, ending a marriage legally required its own individual Act of Parliament, putting it far beyond the reach of all but the wealthy.",
  },
  {
    year: 1882,
    date: "18 August 1882",
    theme: "Social Reform",
    title: "Married Women's Property Act 1882",
    result: "Passed",
    outcome: "achieved",
    detail: "Let married women own and control property and earnings in their own right for the first time, rather than everything automatically becoming their husband's on marriage.",
  },
  {
    year: 1884,
    date: "6 December 1884",
    theme: "Democratic Reform",
    title: "Representation of the People Act 1884 (the \"Third Reform Act\")",
    result: "Passed",
    outcome: "achieved",
    detail: "Extended the household franchise from the towns to the countryside, roughly doubling the electorate again and bringing most male agricultural workers the vote for the first time.",
  },
  {
    year: 1885,
    date: "25 June 1885",
    theme: "Democratic Reform",
    title: "Redistribution of Seats Act 1885",
    result: "Passed",
    outcome: "achieved",
    detail: "Companion legislation to the Third Reform Act — replaced most multi-member constituencies with single-member seats of broadly equal size, the direct ancestor of today's constituency map.",
  },
  {
    year: 1885,
    date: "8 June 1885",
    theme: "Confidence",
    title: "Defeat of Gladstone's second government on the Budget",
    result: "Lost",
    outcome: "not_kept",
    detail: "An amendment to the Budget was carried against the government, and Gladstone resigned rather than carry on — a reminder that budget votes have long doubled as tests of a government's authority.",
  },
  {
    year: 1911,
    date: "16 December 1911",
    theme: "Economic",
    title: "National Insurance Act 1911",
    result: "Passed",
    outcome: "achieved",
    detail: "Lloyd George's flagship reform — created the UK's first compulsory unemployment and health insurance schemes, funded by workers, employers and the state together. A direct forerunner of the modern welfare state.",
  },
  {
    year: 1946,
    date: "12 July 1946",
    theme: "Economic",
    title: "Coal Industry Nationalisation Act 1946",
    result: "Passed",
    outcome: "achieved",
    detail: "Brought Britain's coal mines under state ownership as the National Coal Board — the first and, for decades, most politically totemic of Attlee's nationalisations.",
  },
  {
    year: 1948,
    date: "30 June 1948",
    theme: "Democratic Reform",
    title: "Representation of the People Act 1948",
    result: "Passed",
    outcome: "achieved",
    detail: "Abolished the last surviving forms of plural voting — extra votes for university graduates and business property owners — finally making it one person, one vote in UK general elections.",
  },
  {
    year: 1976,
    date: "22 November 1976",
    theme: "Social Reform",
    title: "Race Relations Act 1976",
    result: "Passed",
    outcome: "achieved",
    detail: "Consolidated and strengthened earlier, weaker race discrimination laws from 1965 and 1968, and created the Commission for Racial Equality to enforce them.",
  },
  {
    year: 1980,
    date: "1 August 1980",
    theme: "Economic",
    title: "Employment Act 1980",
    result: "Passed",
    outcome: "achieved",
    detail: "The first in Margaret Thatcher's run of trade union reform — restricted secondary picketing and made \"closed shops\" (jobs that required union membership) harder to enforce.",
  },
  {
    year: 1984,
    date: "12 April 1984",
    theme: "Economic",
    title: "Telecommunications Act 1984",
    result: "Passed",
    outcome: "achieved",
    detail: "Privatised British Telecom, the first of the major 1980s privatisations of state-owned industry — gas, water, and the rest followed over the rest of the decade.",
  },
  {
    year: 1986,
    date: "7 November 1986",
    theme: "Economic",
    title: "Financial Services Act 1986",
    result: "Passed",
    outcome: "achieved",
    detail: "The legal underpinning of the \"Big Bang\" — deregulated the London Stock Exchange and abolished fixed commissions, transforming the City of London into a global financial centre almost overnight.",
  },
  {
    year: 1986,
    date: "22 July 1986",
    theme: "Europe",
    title: "European Communities (Amendment) Act 1986",
    result: "Passed",
    outcome: "achieved",
    detail: "Ratified the Single European Act, the first major overhaul of the EEC's founding treaties — deepened integration by extending qualified majority voting and setting a 1992 deadline for the EU single market.",
  },
  {
    year: 1989,
    date: "16 November 1989",
    theme: "Social Reform",
    title: "Children Act 1989",
    result: "Passed",
    outcome: "achieved",
    detail: "Rewrote the law on child welfare and custody around a single guiding principle — that the child's welfare is paramount — still the foundation of UK family and child protection law today.",
  },
  {
    year: 1991,
    date: "21 January 1991",
    theme: "Foreign Policy & War",
    title: "Commons debate authorising British forces in the Gulf War",
    result: "Passed by a large majority",
    outcome: "achieved",
    detail: "MPs backed UK participation in the US-led coalition to expel Iraqi forces from Kuwait, with both government and official opposition support — a rare moment of near-unanimity on the use of military force.",
  },
  {
    year: 1998,
    date: "31 July 1998",
    theme: "Constitutional",
    title: "Government of Wales Act 1998",
    result: "Passed",
    outcome: "achieved",
    detail: "Established the National Assembly for Wales (now the Senedd), the devolution settlement running alongside the Scotland Act passed the same year.",
  },
  {
    year: 1998,
    date: "19 November 1998",
    theme: "Constitutional",
    title: "Northern Ireland Act 1998",
    result: "Passed",
    outcome: "achieved",
    detail: "Gave legal effect to the Good Friday Agreement, establishing the Northern Ireland Assembly and its power-sharing structure between unionist and nationalist parties.",
  },
  {
    year: 2000,
    date: "14 June 2000",
    theme: "Economic",
    title: "Financial Services and Markets Act 2000",
    result: "Passed",
    outcome: "achieved",
    detail: "Created the Financial Services Authority, the UK's first single regulator covering the whole financial sector — later broken up into the FCA and PRA after the 2008 crisis exposed its limits.",
  },
  {
    year: 2000,
    date: "30 November 2000",
    theme: "Constitutional",
    title: "Freedom of Information Act 2000",
    result: "Passed",
    outcome: "achieved",
    detail: "Gave the public a legal right to request information held by public bodies — including, famously, the 2009 disclosures on MPs' expenses that this site's own subject matter grew directly out of.",
  },
  {
    year: 2000,
    date: "30 November 2000",
    theme: "Democratic Reform",
    title: "Political Parties, Elections and Referendums Act 2000",
    result: "Passed",
    outcome: "achieved",
    detail: "Created the Electoral Commission and set the modern rules on political donations and campaign spending — the framework every declared donation on this site's own Donors & Lobbying page is regulated under.",
  },
  {
    year: 2008,
    date: "19 June 2008",
    theme: "Europe",
    title: "European Union (Amendment) Act 2008",
    result: "Passed",
    outcome: "achieved",
    detail: "Ratified the Lisbon Treaty without the public referendum Labour had promised for its near-identical predecessor, the EU Constitution — a decision that fuelled years of Conservative and UKIP pressure for an in/out referendum.",
  },
  {
    year: 2013,
    date: "25 April 2013",
    theme: "Constitutional",
    title: "Succession to the Crown Act 2013",
    result: "Passed",
    outcome: "achieved",
    detail: "Ended centuries of male-preference primogeniture, so the eldest royal child inherits the throne regardless of sex, and removed the bar on the monarch marrying a Catholic.",
  },
  {
    year: 2013,
    date: "31 January 2013",
    theme: "Democratic Reform",
    title: "Electoral Registration and Administration Act 2013",
    result: "Passed",
    outcome: "achieved",
    detail: "Replaced household voter registration (one person registering a whole address) with individual electoral registration — intended to cut fraud, though critics warned, correctly, that it would initially shrink the electoral roll.",
  },
  {
    year: 2018,
    date: "26 June 2018",
    theme: "Constitutional",
    title: "European Union (Withdrawal) Act 2018",
    result: "Passed",
    outcome: "achieved",
    detail: "The technical core of Brexit — converted the whole existing body of EU law into UK domestic law at the moment of exit, so nothing simply vanished overnight, and gave ministers wide powers to amend it afterwards.",
  },
  {
    year: 2019,
    date: "27 March 2019",
    theme: "Europe",
    title: "\"Indicative votes\" on alternative Brexit outcomes",
    result: "No option won a majority",
    outcome: "not_kept",
    detail: "With Theresa May's deal repeatedly rejected, backbenchers seized control of the Commons agenda to test alternatives — customs union, a second referendum, revoking Article 50 — across two rounds of votes. Every single option was defeated, starkly illustrating Parliament's deadlock.",
  },
  {
    year: 2019,
    date: "4 September 2019",
    theme: "Confidence",
    title: "Motion for an early general election under the Fixed-term Parliaments Act",
    result: "Failed to reach the required two-thirds majority",
    outcome: "not_kept",
    detail: "Boris Johnson tried to force a snap election to break the Brexit deadlock, but the Fixed-term Parliaments Act (see the Constitutional tab) required a two-thirds majority he couldn't reach — MPs voted to deny him one rather than trigger a \"no-deal by default\" election timetable.",
  },
];


// Every government formation since Robert Walpole in 1721, conventionally
// treated as the first Prime Minister even though the title itself wasn't
// used officially until much later. Where the same person led more than one
// distinct government (a resignation and later return, not just a reshuffle),
// each formation gets its own entry, matching how "list of UK governments"
// is normally counted. Years only, not exact days, for anything before the
// 20th century — that level of precision isn't something we're confident
// enough in to state as fact.
export const GOVERNMENTS = [
  { year: 1721, pm: "Robert Walpole", party: "Whig", note: "Conventionally regarded as the first Prime Minister, though the title didn't exist officially yet.", events: ["Britain's longest continuously serving PM — 21 years in office", "Steered the country through the 1720 South Sea Bubble financial crash", "Established many of the working conventions of Cabinet government"] },
  { year: 1742, pm: "Earl of Wilmington", party: "Whig", note: "Led a Whig government.", events: ["A caretaker figure — Walpole's old rivals, not Wilmington himself, effectively ran the government", "Died in office after less than a year"] },
  { year: 1743, pm: "Henry Pelham", party: "Whig", note: "Led a Whig government.", events: ["Brought political stability after years of factional infighting", "Reduced the national debt and largely kept Britain at peace", "His death in 1754 famously prompted George II to say \"Now I shall have no more peace\""] },
  { year: 1754, pm: "Duke of Newcastle", party: "Whig", note: "Led a Whig government.", events: ["Struggled to manage the outbreak of the Seven Years' War", "Resigned in 1756 after early wartime setbacks"] },
  { year: 1756, pm: "Duke of Devonshire", party: "Whig", note: "Brief wartime ministry during the Seven Years' War.", events: ["A brief wartime caretaker government", "Paved the way for the Pitt–Newcastle coalition that followed"] },
  { year: 1757, pm: "Duke of Newcastle", party: "Whig", note: "Returned to office in coalition with William Pitt the Elder to prosecute the Seven Years' War.", events: ["Formed a coalition with William Pitt the Elder, who ran the war effort", "Britain won major victories in the Seven Years' War, including the capture of Quebec in 1759"] },
  { year: 1762, pm: "Earl of Bute", party: "Tory", note: "Negotiated the 1763 Treaty of Paris ending the Seven Years' War.", events: ["Negotiated the 1763 Treaty of Paris, ending the Seven Years' War", "Deeply unpopular; resigned after less than a year"] },
  { year: 1763, pm: "George Grenville", party: "Whig", note: "Passed the Stamp Act 1765, taxing the American colonies and helping trigger the road to American independence.", events: ["Introduced the Stamp Act 1765, taxing American colonists directly", "Sparked the \"no taxation without representation\" protests that led toward American independence"] },
  { year: 1765, pm: "Marquess of Rockingham", party: "Whig", note: "Repealed the Stamp Act in 1766 amid colonial protest.", events: ["Repealed the deeply unpopular Stamp Act in 1766", "A short-lived, relatively weak ministry"] },
  { year: 1766, pm: "William Pitt the Elder", party: "Whig", note: "Earl of Chatham; already famous as a wartime leader, his premiership itself was hampered by ill health.", events: ["Already famous as the architect of Britain's Seven Years' War victories", "Illness left him largely absent from government for much of his own premiership"] },
  { year: 1768, pm: "Duke of Grafton", party: "Whig", note: "Presided over rising tension with the American colonies, including the Townshend Acts.", events: ["Presided over rising tension with the American colonies, including the Townshend Acts", "Resigned in 1770 amid growing political and personal scandal"] },
  { year: 1770, pm: "Lord North", party: "Tory", note: "Led Britain through the American Revolutionary War, resigning in 1782 after defeat at Yorktown.", events: ["Led Britain through the American Revolutionary War", "Oversaw the Boston Tea Party in 1773 and the loss of the American colonies", "Resigned in 1782 after British defeat at Yorktown"] },
  { year: 1782, pm: "Marquess of Rockingham", party: "Whig", note: "Returned to office to negotiate peace with America; died in office months later.", events: ["Returned to office to begin peace negotiations with America", "Died in office just months later"] },
  { year: 1782, pm: "Earl of Shelburne", party: "Whig", note: "Negotiated the 1783 Treaty of Paris recognising American independence.", events: ["Negotiated the 1783 Treaty of Paris, formally recognising American independence", "Brought down by his own fractious coalition within months"] },
  { year: 1783, pm: "Duke of Portland", party: "Coalition", note: "The short-lived \"Fox–North Coalition,\" dismissed by the King within months.", events: ["The short-lived \"Fox–North Coalition\"", "Dismissed by King George III within months, seen by the Crown as illegitimate"] },
  { year: 1783, pm: "William Pitt the Younger", party: "Tory", note: "Became PM at 24; oversaw the 1800 Union with Ireland and financed Britain's early wars against Revolutionary France.", events: ["Became PM at 24 — still the youngest in British history", "Financed Britain's early wars against Revolutionary France", "Passed the Act of Union with Ireland in 1800"] },
  { year: 1801, pm: "Henry Addington", party: "Tory", note: "Negotiated the 1802 Peace of Amiens, a brief pause in the wars with France.", events: ["Negotiated the 1802 Peace of Amiens, a temporary pause in the wars with France", "War resumed in 1803, and his government fell the following year"] },
  { year: 1804, pm: "William Pitt the Younger", party: "Tory", note: "Returned to lead the war against Napoleon until his death in office in 1806.", events: ["Formed the Third Coalition against Napoleon", "Died in office in 1806, exhausted by the strain of wartime leadership"] },
  { year: 1806, pm: "Lord Grenville", party: "Whig", note: "The \"Ministry of All the Talents\" — passed the Slave Trade Act 1807, abolishing Britain's participation in the transatlantic slave trade.", events: ["The \"Ministry of All the Talents\" — a broad coalition government", "Passed the Slave Trade Act 1807, abolishing Britain's participation in the transatlantic slave trade"] },
  { year: 1807, pm: "Duke of Portland", party: "Tory", note: "Continued the war against Napoleon.", events: ["Continued the war against Napoleon", "Marked by a bitter duel between two of his own ministers, Canning and Castlereagh"] },
  { year: 1809, pm: "Spencer Perceval", party: "Tory", note: "The only British Prime Minister ever assassinated — shot in the House of Commons lobby in 1812.", events: ["The only British Prime Minister ever assassinated — shot in the Commons lobby in 1812", "Governed through the ongoing Napoleonic Wars"] },
  { year: 1812, pm: "Earl of Liverpool", party: "Tory", note: "The 19th century's longest-serving PM (15 years) — saw Waterloo, the Peterloo Massacre, and growing pressure for reform.", events: ["The 19th century's longest-serving PM, at 15 years", "Saw victory at Waterloo in 1815 and the peace that followed", "Governed through the Peterloo Massacre (1819) and growing pressure for reform"] },
  { year: 1827, pm: "George Canning", party: "Tory", note: "Died in office after less than four months — the shortest premiership until Liz Truss, 195 years later.", events: ["Died in office after less than four months", "The shortest premiership in British history until Liz Truss, 195 years later"] },
  { year: 1827, pm: "Viscount Goderich", party: "Tory", note: "Resigned without ever facing Parliament as PM.", events: ["Resigned without ever facing Parliament as PM", "Unable to hold his fractious Cabinet together"] },
  { year: 1828, pm: "Duke of Wellington", party: "Tory", note: "The victor of Waterloo; passed Catholic Emancipation in 1829 despite his own party's opposition.", events: ["The victor of Waterloo against Napoleon in 1815", "Passed Catholic Emancipation in 1829 despite his own party's opposition"] },
  { year: 1830, pm: "Earl Grey", party: "Whig", note: "Passed the Great Reform Act 1832 and the Slavery Abolition Act 1833.", events: ["Passed the Great Reform Act 1832, the first major expansion of the franchise", "Passed the Slavery Abolition Act 1833"] },
  { year: 1834, pm: "Viscount Melbourne", party: "Whig", note: "Became a close mentor to the young Queen Victoria after her 1837 accession.", events: ["A brief first ministry, ended when William IV dismissed him and called on Peel"] },
  { year: 1834, pm: "Robert Peel", party: "Conservative", note: "A brief \"Hundred Days\" ministry; issued the Tamworth Manifesto, the founding document of the modern Conservative Party.", events: ["A brief \"Hundred Days\" ministry", "Issued the Tamworth Manifesto, the founding document of the modern Conservative Party"] },
  { year: 1835, pm: "Viscount Melbourne", party: "Whig", note: "Returned to office for Victoria's early reign.", events: ["Returned to office for the young Queen Victoria's early reign", "Became a close personal mentor to the new Queen"] },
  { year: 1841, pm: "Robert Peel", party: "Conservative", note: "Repealed the Corn Laws in 1846, splitting the Conservative Party for a generation.", events: ["Repealed the Corn Laws in 1846, opening Britain to free trade in food", "As Home Secretary had earlier created London's modern police force", "The Corn Laws repeal split the Conservative Party for a generation"] },
  { year: 1846, pm: "Lord John Russell", party: "Whig", note: "Governed through the Irish Famine, a response widely criticised as inadequate.", events: ["Governed through the Irish Famine (1845–1852), a response widely criticised as inadequate", "Repealed the Navigation Acts, further opening Britain to free trade"] },
  { year: 1852, pm: "Earl of Derby", party: "Conservative", note: "The first of three separate Derby governments.", events: ["A brief minority Conservative government", "The first of three separate Derby ministries"] },
  { year: 1852, pm: "Earl of Aberdeen", party: "Peelite", note: "Led Britain into the Crimean War in 1853.", events: ["Led Britain into the Crimean War in 1853", "His government fell in 1855 amid public anger over the war's mismanagement"] },
  { year: 1855, pm: "Viscount Palmerston", party: "Liberal", note: "Known for assertive \"gunboat diplomacy\" abroad.", events: ["Known for assertive \"gunboat diplomacy\" abroad", "Governed through the aftermath of the Crimean War"] },
  { year: 1858, pm: "Earl of Derby", party: "Conservative", note: "A second, short-lived minority government.", events: ["A second short-lived minority government"] },
  { year: 1859, pm: "Viscount Palmerston", party: "Liberal", note: "Returned to office until his death in 1865.", events: ["Returned to office until his death in 1865", "Presided over a long period of mid-Victorian prosperity"] },
  { year: 1865, pm: "Earl Russell", party: "Liberal", note: "Attempted parliamentary reform; resigned when it failed.", events: ["Attempted further parliamentary reform, which failed and brought down his government"] },
  { year: 1866, pm: "Earl of Derby", party: "Conservative", note: "His third ministry passed the Second Reform Act 1867, roughly doubling the electorate.", events: ["His third ministry passed the Second Reform Act 1867, roughly doubling the electorate", "Disraeli, as Chancellor, did much of the political work of steering the Act through"] },
  { year: 1868, pm: "Benjamin Disraeli", party: "Conservative", note: "A brief first term, succeeding Derby; lost the 1868 election to Gladstone within months.", events: ["A brief first term, inheriting the government from the retiring Derby", "Lost the 1868 general election to Gladstone within months"] },
  { year: 1868, pm: "William Gladstone", party: "Liberal", note: "His first government disestablished the Church of Ireland and passed the Ballot Act 1872, introducing the secret ballot.", events: ["Disestablished the Church of Ireland", "Passed the Ballot Act 1872, introducing the secret ballot", "Reformed the civil service and the army"] },
  { year: 1874, pm: "Benjamin Disraeli", party: "Conservative", note: "Expanded the British Empire and social reform legislation on housing and public health.", events: ["Made Queen Victoria \"Empress of India\" in 1876", "Expanded the British Empire during the \"Scramble for Africa\"", "Passed social reform on housing and public health"] },
  { year: 1880, pm: "William Gladstone", party: "Liberal", note: "His second government passed the Third Reform Act 1884, extending the franchise to most male agricultural workers.", events: ["Passed the Third Reform Act 1884, extending the franchise further", "Faced the Mahdist War and the death of General Gordon at Khartoum"] },
  { year: 1885, pm: "Marquess of Salisbury", party: "Conservative", note: "The first of three separate Salisbury governments.", events: ["A brief minority government pending the next general election"] },
  { year: 1886, pm: "William Gladstone", party: "Liberal", note: "His third government fell within months after his first Irish Home Rule Bill was defeated.", events: ["His first Irish Home Rule Bill was defeated, ending this government within months"] },
  { year: 1886, pm: "Marquess of Salisbury", party: "Conservative", note: "A long period of Conservative dominance amid the imperial \"Scramble for Africa.\"", events: ["A long period of Conservative dominance amid the imperial \"Scramble for Africa\""] },
  { year: 1892, pm: "William Gladstone", party: "Liberal", note: "His fourth and final government passed a second Home Rule Bill through the Commons, only for the Lords to reject it.", events: ["A second Home Rule Bill passed the Commons but was rejected by the Lords", "Resigned in 1894, aged 84 — the oldest serving PM in history"] },
  { year: 1894, pm: "Earl of Rosebery", party: "Liberal", note: "A short, troubled premiership amid deep Liberal Party divisions.", events: ["A troubled premiership amid deep Liberal Party divisions", "Resigned within a year, worn down by internal party conflict"] },
  { year: 1895, pm: "Marquess of Salisbury", party: "Conservative", note: "His third government saw continued imperial expansion into the new century.", events: ["Presided over the British Empire at its territorial height", "Governed through the Second Boer War (1899–1902)"] },
  { year: 1902, pm: "Arthur Balfour", party: "Conservative", note: "Passed the Education Act 1902; resigned in 1905 amid a party split over trade tariffs.", events: ["Passed the Education Act 1902, reorganising schooling in England and Wales", "Signed the Entente Cordiale with France in 1904", "Resigned in 1905 amid a bitter party split over trade tariffs"] },
  { year: 1905, pm: "Henry Campbell-Bannerman", party: "Liberal", note: "The first to officially hold the title \"Prime Minister\"; began the Liberal welfare reforms.", events: ["The first to officially hold the title \"Prime Minister\"", "Began the Liberal welfare reforms later expanded by Asquith and Lloyd George"] },
  { year: 1908, pm: "H. H. Asquith", party: "Liberal", note: "Passed the 1909 \"People's Budget\" and the Parliament Act 1911, and led Britain into the First World War in 1914.", events: ["Passed the 1909 \"People's Budget\" and the Parliament Act 1911", "Led Britain into the First World War in 1914", "Replaced by Lloyd George in 1916 amid a wartime political crisis"] },
  { year: 1916, pm: "David Lloyd George", party: "Liberal (Coalition)", note: "Led the wartime coalition to victory in 1918, then passed the Representation of the People Act 1918.", events: ["Led the wartime coalition to victory in 1918", "Passed the Representation of the People Act 1918, nearly tripling the electorate", "Negotiated the 1921 Anglo-Irish Treaty, creating the Irish Free State"] },
  { year: 1922, pm: "Bonar Law", party: "Conservative", note: "Resigned after seven months due to terminal illness — sometimes called \"the unknown Prime Minister.\"", events: ["Resigned after seven months due to terminal illness", "Sometimes called \"the unknown Prime Minister\""] },
  { year: 1923, pm: "Stanley Baldwin", party: "Conservative", note: "The first of three separate Baldwin governments.", events: ["Called a snap election over trade tariffs and lost his majority within months"] },
  { year: 1924, pm: "Ramsay MacDonald", party: "Labour", note: "The first-ever Labour government — a minority administration that fell the same year over the Campbell Case.", events: ["Britain's first-ever Labour government — a minority administration", "Fell the same year over the \"Campbell Case\""] },
  { year: 1924, pm: "Stanley Baldwin", party: "Conservative", note: "Governed through the 1926 General Strike.", events: ["Governed through the 1926 General Strike", "Passed the Representation of the People (Equal Franchise) Act 1928"] },
  { year: 1929, pm: "Ramsay MacDonald", party: "Labour", note: "A second minority Labour government, overwhelmed by the Great Depression from 1929.", events: ["A second minority Labour government", "Overwhelmed by the Great Depression from late 1929"] },
  { year: 1931, pm: "Ramsay MacDonald", party: "National Government", note: "Formed a cross-party National Government to handle the economic crisis, splitting from and being expelled by his own Labour Party.", events: ["Formed a cross-party National Government to handle the economic crisis", "Expelled from the Labour Party he had once led"] },
  { year: 1935, pm: "Stanley Baldwin", party: "National Government", note: "His third government managed the 1936 abdication crisis of Edward VIII.", events: ["Managed the 1936 abdication crisis of Edward VIII", "Began UK rearmament in the face of rising Nazi Germany"] },
  { year: 1937, pm: "Neville Chamberlain", party: "National Government", note: "Pursued the policy of appeasement, including the 1938 Munich Agreement, before declaring war on Germany in September 1939.", events: ["Pursued the policy of \"appeasement\", including the 1938 Munich Agreement", "Declared war on Germany on 3 September 1939", "Resigned in May 1940 after the failed Norway campaign"] },
  { year: 1940, pm: "Winston Churchill", party: "Conservative (Coalition)", note: "Led the wartime coalition government to victory in Europe in 1945, then lost that year's general election to Labour.", events: ["Led Britain through the Second World War", "Rallied the country with landmark wartime speeches", "Lost the 1945 general election to Labour despite victory in Europe"] },
  { year: 1945, pm: "Clement Attlee", party: "Labour", note: "Created the NHS and the modern welfare state, nationalised the Bank of England, coal and rail, and granted Indian independence in 1947.", events: ["Created the NHS, launched on 5 July 1948", "Nationalised the Bank of England, coal mines and railways", "Granted Indian independence in 1947"] },
  { year: 1951, pm: "Winston Churchill", party: "Conservative", note: "A quieter second term; suffered a serious stroke in office before handing over to Eden.", events: ["A quieter second term focused on post-war recovery", "Suffered a serious stroke in office in 1953, kept largely secret at the time"] },
  { year: 1955, pm: "Anthony Eden", party: "Conservative", note: "Resigned in 1957 after the disastrous 1956 Suez Crisis badly damaged Britain's international standing.", events: ["Led the disastrous 1956 Suez Crisis, badly damaging Britain's international standing", "Resigned in 1957 amid the fallout and ill health"] },
  { year: 1957, pm: "Harold Macmillan", party: "Conservative", note: "Presided over African decolonisation (\"the wind of change\") before resigning in 1963 amid the Profumo scandal and ill health.", events: ["Gave the \"Wind of Change\" speech on African decolonisation in 1960", "Presided over rising post-war prosperity — \"never had it so good\"", "Resigned in 1963 amid the Profumo scandal"] },
  { year: 1963, pm: "Sir Alec Douglas-Home", party: "Conservative", note: "A brief premiership; narrowly lost the 1964 election to Harold Wilson.", events: ["A brief premiership of less than a year", "Narrowly lost the 1964 general election to Harold Wilson"] },
  { year: 1964, pm: "Harold Wilson", party: "Labour", note: "His first government passed the death penalty suspension, the Sexual Offences Act, and the Abortion Act, and devalued the pound in 1967.", events: ["Legalised abortion, decriminalised homosexuality, and suspended the death penalty", "Devalued the pound in 1967", "Established the Open University in 1969"] },
  { year: 1970, pm: "Edward Heath", party: "Conservative", note: "Took the UK into the EEC in 1973, but was brought down by the 1973–74 miners' strike and the three-day week.", events: ["Took the UK into the European Economic Community in 1973", "Faced the 1973–74 miners' strike and introduced the three-day week", "Lost both general elections held in 1974"] },
  { year: 1974, pm: "Harold Wilson", party: "Labour", note: "A second period in office; renegotiated EEC terms ahead of the 1975 referendum, then resigned unexpectedly in 1976.", events: ["Renegotiated EEC membership terms ahead of the UK's first referendum, in 1975", "Resigned unexpectedly in 1976, surprising Westminster"] },
  { year: 1976, pm: "James Callaghan", party: "Labour", note: "Governed through the strike-hit \"Winter of Discontent\" and lost the 1979 confidence vote by a single vote.", events: ["Governed through the strike-hit \"Winter of Discontent\" of 1978–79", "Lost a Commons confidence vote by a single vote in March 1979"] },
  { year: 1979, pm: "Margaret Thatcher", party: "Conservative", note: "The UK's first woman PM; the Falklands War, the miners' strike, Right to Buy, and a wave of privatisation defined her 11 years in office.", events: ["The UK's first woman Prime Minister", "Won the 1982 Falklands War", "Defeated the 1984–85 miners' strike", "Privatised state industries including British Telecom and British Gas", "The Community Charge (\"poll tax\") contributed to her downfall in 1990"] },
  { year: 1990, pm: "John Major", party: "Conservative", note: "Ratified the Maastricht Treaty amid fierce party rebellion, survived Black Wednesday in 1992, and lost the 1997 landslide to Blair.", events: ["Ratified the Maastricht Treaty amid fierce Conservative rebellion", "Survived \"Black Wednesday\" in 1992, when the pound crashed out of the ERM", "Lost the 1997 election in a landslide to Tony Blair"] },
  { year: 1997, pm: "Tony Blair", party: "Labour", note: "Delivered Scottish and Welsh devolution, the Human Rights Act, the Good Friday Agreement, and the 2003 Iraq War.", events: ["Delivered devolution to Scotland and Wales", "Brokered the Good Friday Agreement in Northern Ireland, 1998", "Passed the Human Rights Act 1998", "Joined the US-led invasion of Iraq in 2003, his most controversial decision"] },
  { year: 2007, pm: "Gordon Brown", party: "Labour", note: "Led the response to the 2008 global financial crisis, including the Northern Rock nationalisation.", events: ["Led the UK's response to the 2008 global financial crisis", "Nationalised Northern Rock and bailed out major banks", "Lost the 2010 election, resulting in a hung parliament"] },
  { year: 2010, pm: "David Cameron", party: "Conservative (Coalition)", note: "The first coalition government since WWII, with the Liberal Democrats; called the 2016 EU referendum and resigned when Leave won.", events: ["Formed the first coalition government since WWII, with the Liberal Democrats", "Introduced austerity spending cuts", "Called the 2014 Scottish independence referendum — No won", "Called the 2016 EU referendum and resigned when Leave won"] },
  { year: 2016, pm: "Theresa May", party: "Conservative", note: "Triggered Article 50, lost her majority in a snap 2017 election, and resigned in 2019 after Parliament repeatedly rejected her Brexit deal.", events: ["Triggered Article 50 to begin the Brexit process", "Lost her Commons majority in a snap 2017 election", "Her Brexit withdrawal deal was rejected by Parliament three times", "Resigned in 2019"] },
  { year: 2019, pm: "Boris Johnson", party: "Conservative", note: "Won a landslide on \"Get Brexit Done,\" completed the UK's EU withdrawal, led the COVID-19 response, and resigned in 2022 over the \"Partygate\" scandal.", events: ["Won a landslide in 2019 on \"Get Brexit Done\"", "Completed the UK's departure from the EU on 31 January 2020", "Led the UK through the COVID-19 pandemic", "Resigned in 2022 following the \"Partygate\" scandal"] },
  { year: 2022, pm: "Liz Truss", party: "Conservative", note: "The shortest-serving PM in British history — 49 days — after her mini-budget triggered a market crisis.", events: ["The shortest-serving PM in British history — 49 days", "Her mini-budget triggered a market crisis and a collapse in the pound", "Resigned after losing the confidence of her own party"] },
  { year: 2022, pm: "Rishi Sunak", party: "Conservative", note: "The UK's first British Asian PM; called and lost the July 2024 general election.", events: ["The UK's first British Asian Prime Minister", "Focused on stabilising the economy after the Truss mini-budget", "Called and lost the July 2024 general election"] },
  { year: 2024, pm: "Keir Starmer", party: "Labour", note: "Won a landslide in July 2024, ending 14 years of Conservative government.", events: ["Won a landslide general election victory in July 2024", "Ended 14 years of Conservative government"] },
  { year: 2026, pm: "Andy Burnham", party: "Labour", note: "Became Prime Minister in July 2026. This is drawn directly from this site's own live Cabinet data, not a separately verified historical source — treat the surrounding circumstances with appropriate caution.", events: ["Became Prime Minister in July 2026, per this site's own live data"] },
];

export const OUTCOME_COLOR = { achieved: "#2F6F4E", not_kept: "#9C3B3B" };
